<?php
declare(strict_types=1);
use App\Controllers\HomeController;
use App\Controllers\ProductController;
use App\Controllers\CartController;
use App\Controllers\CheckoutController;
use App\Controllers\AuthController;
use App\Controllers\AccountController;
use App\Controllers\AdminController;

$router->get('home', [HomeController::class, 'index']);
$router->get('products', [ProductController::class, 'index']);
$router->get('product', [ProductController::class, 'show']);
$router->get('cart', [CartController::class, 'index']);
$router->get('checkout', [CheckoutController::class, 'index']);
$router->post('checkout', [CheckoutController::class, 'place']);
$router->get('order-success', [CheckoutController::class, 'success']);
$router->get('login', [AuthController::class, 'login']);
$router->post('login', [AuthController::class, 'login']);
$router->get('register', [AuthController::class, 'register']);
$router->post('register', [AuthController::class, 'register']);
$router->post('logout', [AuthController::class, 'logout']);
$router->get('account', [AccountController::class, 'index'], ['Admin', 'User']);
$router->get('orders', [AccountController::class, 'orders'], ['Admin', 'User']);
$router->get('order', [AccountController::class, 'show'], ['Admin', 'User']);
$router->get('admin', [AdminController::class, 'index'], ['Admin']);
$router->get('admin-products', [AdminController::class, 'products'], ['Admin']);
$router->get('admin-product', [AdminController::class, 'productForm'], ['Admin']);
$router->post('admin-product', [AdminController::class, 'productForm'], ['Admin']);
$router->post('admin-product-delete', [AdminController::class, 'deleteProduct'], ['Admin']);
$router->get('admin-catalog', [AdminController::class, 'catalog'], ['Admin']);
$router->post('admin-catalog', [AdminController::class, 'catalog'], ['Admin']);
$router->post('admin-catalog-delete', [AdminController::class, 'deleteCatalog'], ['Admin']);
$router->get('admin-orders', [AdminController::class, 'orders'], ['Admin']);
$router->get('admin-order', [AdminController::class, 'order'], ['Admin']);
$router->post('admin-order', [AdminController::class, 'order'], ['Admin']);
$router->get('admin-users', [AdminController::class, 'users'], ['Admin']);
$router->post('admin-users', [AdminController::class, 'users'], ['Admin']);
$router->get('admin-logs', [AdminController::class, 'logs'], ['Admin']);
