<p class="admin-intro">Sắp xếp thông tin sách để khách hàng dễ tìm kiếm và khám phá.</p>
<?php if ($error): ?><div class="admin-alert is-error" role="alert"><?= e($error) ?></div><?php endif; ?>
<div class="admin-catalog-grid"><section class="admin-panel">
    <form class="admin-filters" method="get" action="<?= e(base_url() . '/index.php') ?>"><input type="hidden" name="route" value="admin-catalog"><input type="hidden" name="kind" value="<?= e($kind) ?>"><div class="admin-search"><?= icon('search') ?><input name="q" type="search" aria-label="Tìm danh mục" value="<?= e(query('q')) ?>" placeholder="Tìm theo tên…" maxlength="100"></div><button class="button button-outline">Tìm kiếm</button></form>
    <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Mã</th><th>Tên</th><th>Đầu sách</th><th>Thao tác</th></tr></thead><tbody>
    <?php foreach ($listing['rows'] as $row): ?><tr><td>#<?= e($row['id']) ?></td><td class="admin-name"><?= e($row['name']) ?></td><td><?= e($row['books']) ?></td><td><div class="admin-row-actions"><a class="admin-link" href="<?= e(url('admin-catalog', ['kind' => $kind, 'id' => $row['id']])) ?>">Sửa</a><form method="post" action="<?= e(url('admin-catalog-delete', ['kind' => $kind])) ?>" data-confirm="Bạn muốn xóa mục này?"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($row['id']) ?>"><button class="admin-danger">Xóa</button></form></div></td></tr><?php endforeach; ?>
    <?php if (!$listing['rows']): ?><tr><td colspan="4"><div class="admin-empty"><h3>Chưa có kết quả</h3><p>Thêm mới hoặc thử tìm tên khác.</p></div></td></tr><?php endif; ?>
    </tbody></table></div><?php require ROOT_PATH . '/view/admin/pagination.php'; ?>
    </section><section class="admin-panel admin-form-panel"><h2><?= $item['id'] ? 'Chỉnh sửa' : 'Thêm mới' ?> <?= e(mb_strtolower($title)) ?></h2><form method="post" action="<?= e(url('admin-catalog', ['kind' => $kind] + ($item['id'] ? ['id' => $item['id']] : []))) ?>"><?= csrf_field() ?><div class="field"><label for="catalog-name">Tên <?= e(mb_strtolower($title)) ?> *</label><input id="catalog-name" name="name" required minlength="2" maxlength="<?= e(\App\Models\AdminModel::CATALOGS[$kind][4]) ?>" value="<?= e($item['name']) ?>"></div><button class="button" type="submit">Lưu thông tin</button><?php if ($item['id']): ?> <a class="admin-link" href="<?= e(url('admin-catalog', ['kind' => $kind])) ?>">Hủy sửa</a><?php endif; ?></form><p class="admin-hint">Chỉ xóa được các mục chưa được sử dụng bởi sách.</p></section>
</div>
